basePath: /admin/expense
definitions:
  ptime.TimeResponse:
    properties:
      time:
        type: string
    type: object
  requestmodel.CategoryCreatePayload:
    properties:
      name:
        type: string
    type: object
  requestmodel.CategoryUpdatePayload:
    properties:
      name:
        type: string
    type: object
  requestmodel.LoginPayload:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  requestmodel.RegisterPayload:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      passwordConfirm:
        type: string
    type: object
  responsemodel.CategoryAll:
    properties:
      limit:
        type: integer
      list:
        items:
          $ref: '#/definitions/responsemodel.CategoryBrief'
        type: array
      total:
        type: integer
    type: object
  responsemodel.CategoryBrief:
    properties:
      _id:
        type: string
      createdAt:
        $ref: '#/definitions/ptime.TimeResponse'
      name:
        type: string
    type: object
  responsemodel.CategoryDetail:
    properties:
      _id:
        type: string
      createdAt:
        $ref: '#/definitions/ptime.TimeResponse'
      name:
        type: string
    type: object
  responsemodel.StaffAll:
    properties:
      limit:
        type: integer
      list:
        items:
          $ref: '#/definitions/responsemodel.StaffBrief'
        type: array
      page:
        type: integer
    type: object
  responsemodel.StaffBrief:
    properties:
      _id:
        type: string
      createdAt:
        $ref: '#/definitions/ptime.TimeResponse'
      email:
        type: string
      isRoot:
        type: boolean
      name:
        type: string
      permission:
        items:
          type: string
        type: array
      phone:
        type: string
    type: object
  responsemodel.Upsert:
    properties:
      _id:
        type: string
    type: object
info:
  contact:
    email: buiphuan0211@gmail.com
    name: Dev An Bui
    url: https://github.com/buiphuan0211
  description: |
    All APIs for expenses admin.

    ******************************
    - Add description
    ******************************
  title: manage-expenses - Admin API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      operationId: admin-staff-login
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.LoginPayload'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      operationId: admin-staff-register
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.RegisterPayload'
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Register
      tags:
      - Auth
  /categories:
    get:
      consumes:
      - application/json
      operationId: admin-category-all
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.CategoryAll'
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - Category
    post:
      consumes:
      - application/json
      operationId: admin-category-create
      parameters:
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryCreatePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.Upsert'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Category
  /categories/{id}:
    get:
      consumes:
      - application/json
      operationId: admin-category-detail
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.CategoryDetail'
      security:
      - ApiKeyAuth: []
      summary: Detail
      tags:
      - Category
    put:
      consumes:
      - application/json
      operationId: admin-category-update
      parameters:
      - description: Category id
        in: path
        name: id
        required: true
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryUpdatePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.Upsert'
      security:
      - ApiKeyAuth: []
      summary: Update
      tags:
      - Category
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
  /staffs:
    get:
      consumes:
      - application/json
      operationId: admin-staff-all
      parameters:
      - in: query
        name: keyword
        type: string
      - in: query
        name: limit
        type: integer
      - in: query
        name: page
        type: integer
      - in: query
        name: status
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.StaffAll'
      security:
      - ApiKeyAuth: []
      summary: All
      tags:
      - Staff
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
