basePath: /admin/expense
info:
  contact:
    email: buiphuan0211@gmail.com
    name: Dev An Bui
    url: https://github.com/buiphuan0211
  description: |
    All APIs for expenses admin.

    ******************************
    - Add description
    ******************************
  title: manage-expenses - Admin API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
