definitions:
  requestmodel.CategoryCreatePayload:
    properties:
      name:
        type: string
    type: object
  responsemodel.Upsert:
    properties:
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /categories:
    post:
      consumes:
      - application/json
      operationId: admin-category-create
      parameters:
      - description: Device id
        in: header
        name: device-id
        type: string
      - description: Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/requestmodel.CategoryCreatePayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsemodel.Upsert'
      security:
      - ApiKeyAuth: []
      summary: Create
      tags:
      - Category
  /ping:
    get:
      consumes:
      - application/json
      operationId: ping
      produces:
      - application/json
      responses: {}
      security:
      - ApiKeyAuth: []
      summary: Ping
      tags:
      - Common
swagger: "2.0"
